setwd("C:/Users/gk0036/OneDrive - Agriculture/Documents/R/Plant Health")
library(readr)
library(tidyr)
library(dplyr)

Site<-read_csv("gym_log/form-1__gym-session.csv",
               col_types=cols(created_at=col_skip(),
                              uploaded_at=col_skip(),
                              created_by=col_skip()))
Activity<-read_csv("gym_log/branch-1__activities.csv",
                   col_types=cols(created_at=col_skip(),
                                  uploaded_at=col_skip(),
                                  created_by=col_skip()))

Site<-Site%>%rename(Title=title) # Just need any columns I want to keep for now to be different by R standards. Capitalisation is enough. 

Gym_Log<-merge(Site, Activity, # This merges the data frames by specified shared information. Which means the columns I need to fill with information only present in one or the other are all there and populated correctly! Joy :)
              by.x ="ec5_uuid", # Column name to match from the first data frame
              by.y = "ec5_branch_owner_uuid") # Column name to match from second data frame

# Clean up further
Gym_Log<-Gym_Log%>%
  select(!c("ec5_uuid","ec5_branch_uuid","Title","title"))%>% # I don't need these columns to be super honest, they are generated by combining other columns that already exist so are redundant
  rename(Location="1_Location",
         Date="2_Date",
         Activities="3_Activities",
         Excercise="5_Excercise",
         excerciseNotListed="6_Excercise_not_list",
         Sets="7_Sets",
         Reps="8_Reps",
         Weight_kgs="9_Weight_kgs",
         Time_s="10_Time_s",
         Notes="11_Notes") 

# Lets do some subset summaries for practice. If I wanted to know more about my activity at Genesis Smithfield, how would I get that information?
Grouped<-Gym_Log%>%
  group_by(Location="Genesis Smithfield", 
           Date,
           Excercise)%>%
  summarise(n=n())
